/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "banco.h"

#include <stdlib.h>

struct conta{
	long cpf;
	int senha;
	float val;
};

typedef struct conta conta;

conta contas[50];

int sim_falha()
{
	srand(time(NULL));
	int num = rand() % 2;
	return num;
}

int *
abreconta_1_svc(info *argp, struct svc_req *rqstp)
{
	static int result;

	long cpf = argp->cpf;
	int senha = argp->senha;

	fprintf(stderr, "Requisicao de abertura de conta\n");

	for(int i=0;i<50;i++)
	{
		if(contas[i].cpf == 0)
		{
			contas[i].cpf = cpf;
			contas[i].senha = senha;
			fprintf(stderr, "Conta criada na pos %d : cpf %ld : senha %d\n", i
																		 , contas[i].cpf
																		 , contas[i].senha);
			result = 0;
			break;
		}
		result = 1;
	}

	/*if(sim_falha() == 0)
		return &result;
	else
	{
		printf("Falha na comunicação\n");
		return NULL;
	}*/
	return &result;
}

int *
fechaconta_1_svc(info *argp, struct svc_req *rqstp)
{
	static int  result;

	long cpf = argp->cpf;
	int senha = argp->senha;

	fprintf(stderr, "Requisicao de fechamento de conta\n");

	for(int i=0;i<50;i++)
	{
		if(contas[i].cpf == cpf && contas[i].senha == senha)
		{
			contas[i].cpf = 0;
			contas[i].senha = 0;
			fprintf(stderr, "Conta fechada com sucesso : pos %d\n", i);
			result = 0;
			return &result;
		}
	}

	printf("CPF ou senha inválidos\n");
	result = 1;
	return &result;
}

int *
autentica_1_svc(info *argp, struct svc_req *rqstp)
{
	static int  result;

	long cpf = argp->cpf;
	int senha = argp->senha;

	fprintf(stderr, "Requisicao de autenticação de conta\n");

	for(int i=0;i<50;i++)
	{
		if(contas[i].cpf == cpf && contas[i].senha == senha)
		{
			fprintf(stderr,"Conta autenticada pos %d\n",i);
			result = 0;
			return &result;
		}
	}

	fprintf(stderr,"Conta não existente\n");
	result = 1;
	return &result;
}

int *
deposita_1_svc(dep *argp, struct svc_req *rqstp)
{
	static int  result;

	long cpfDest = argp->cpfDest;
	float  val = argp->val;

	fprintf(stderr, "Requisicao de depósito\n");

	for(int i=0;i<50;i++)
	{
		if(contas[i].cpf == cpfDest)
		{
			contas[i].val += val;
			fprintf(stderr, "Depósito feito com sucesso\n");
			result = 0;
			return &result;
		}
	}

	// TODO: Colocar mecanismo de simulação de falha

	fprintf(stderr, "Conta não existente\n");
	result = 1;
	return &result;
}

int *
retira_1_svc(ret *argp, struct svc_req *rqstp)
{
	static int  result;

	long cpf = argp->cpf;
	int senha = argp->senha;
	float val = argp->val;

	fprintf(stderr, "Requisicao de saque\n");

	for(int i=0;i<50;i++)
	{
		if(contas[i].cpf == cpf && contas[i].senha == senha)
		{
			contas[i].val -= val;
			fprintf(stderr, "Saque feito com sucesso\n");
			result = 0;
			return &result;
		}
	}

	// TODO: Colocar mecanismo de simulação de falha

	fprintf(stderr, "CPF ou senha inválidos!");
	result = 1;
	return &result;
}

int *
consulta_1_svc(info *argp, struct svc_req *rqstp)
{
	static int  result;

	// TODO: Mudar o tipo de retorn pra float e etc

	return &result;
}

int *
deposita_2_svc(dep *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
retira_2_svc(ret *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
consulta_2_svc(info *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
