/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "banco.h"

bool_t
xdr_info (XDR *xdrs, info *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, &objp->cpf))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->senha))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_dep (XDR *xdrs, dep *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, &objp->cpf))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->cpfDest))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->val))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->senha))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ret (XDR *xdrs, ret *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, &objp->cpf))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->val))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->senha))
		 return FALSE;
	return TRUE;
}
