/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "bancoV2.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
banco_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		abre abreconta_1_arg;
		int fechaconta_1_arg;
		info autentica_1_arg;
		dep deposita_1_arg;
		ret retira_1_arg;
		int consulta_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case abreConta:
		_xdr_argument = (xdrproc_t) xdr_abre;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) abreconta_1_svc;
		break;

	case fechaConta:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) fechaconta_1_svc;
		break;

	case autentica:
		_xdr_argument = (xdrproc_t) xdr_info;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) autentica_1_svc;
		break;

	case deposita:
		_xdr_argument = (xdrproc_t) xdr_dep;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) deposita_1_svc;
		break;

	case retira:
		_xdr_argument = (xdrproc_t) xdr_ret;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) retira_1_svc;
		break;

	case consulta:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) consulta_1_svc;
		break;

	case getID:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) getid_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
banco_2(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		dep deposita_2_arg;
		ret retira_2_arg;
		int consulta_2_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case deposita:
		_xdr_argument = (xdrproc_t) xdr_dep;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) deposita_2_svc;
		break;

	case retira:
		_xdr_argument = (xdrproc_t) xdr_ret;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) retira_2_svc;
		break;

	case consulta:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) consulta_2_svc;
		break;

	case getID:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) getid_2_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (BANCO, AGENCIA);
	pmap_unset (BANCO, CAIXA);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, BANCO, AGENCIA, banco_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (BANCO, AGENCIA, udp).");
		exit(1);
	}
	if (!svc_register(transp, BANCO, CAIXA, banco_2, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (BANCO, CAIXA, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, BANCO, AGENCIA, banco_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (BANCO, AGENCIA, tcp).");
		exit(1);
	}
	if (!svc_register(transp, BANCO, CAIXA, banco_2, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (BANCO, CAIXA, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
