/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BANCOV2_H_RPCGEN
#define _BANCOV2_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct abre {
	long cpf;
	int senha;
	int id;
};
typedef struct abre abre;

struct info {
	long cpf;
	int senha;
};
typedef struct info info;

struct dep {
	int numConta;
	float val;
	int id;
};
typedef struct dep dep;

struct ret {
	int numConta;
	float val;
	int id;
};
typedef struct ret ret;

#define BANCO 55555555
#define AGENCIA 1

#if defined(__STDC__) || defined(__cplusplus)
#define abreConta 1
extern  int * abreconta_1(abre *, CLIENT *);
extern  int * abreconta_1_svc(abre *, struct svc_req *);
#define fechaConta 2
extern  int * fechaconta_1(int *, CLIENT *);
extern  int * fechaconta_1_svc(int *, struct svc_req *);
#define autentica 3
extern  int * autentica_1(info *, CLIENT *);
extern  int * autentica_1_svc(info *, struct svc_req *);
#define deposita 4
extern  int * deposita_1(dep *, CLIENT *);
extern  int * deposita_1_svc(dep *, struct svc_req *);
#define retira 5
extern  int * retira_1(ret *, CLIENT *);
extern  int * retira_1_svc(ret *, struct svc_req *);
#define consulta 6
extern  float * consulta_1(int *, CLIENT *);
extern  float * consulta_1_svc(int *, struct svc_req *);
#define getID 7
extern  int * getid_1(void *, CLIENT *);
extern  int * getid_1_svc(void *, struct svc_req *);
extern int banco_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define abreConta 1
extern  int * abreconta_1();
extern  int * abreconta_1_svc();
#define fechaConta 2
extern  int * fechaconta_1();
extern  int * fechaconta_1_svc();
#define autentica 3
extern  int * autentica_1();
extern  int * autentica_1_svc();
#define deposita 4
extern  int * deposita_1();
extern  int * deposita_1_svc();
#define retira 5
extern  int * retira_1();
extern  int * retira_1_svc();
#define consulta 6
extern  float * consulta_1();
extern  float * consulta_1_svc();
#define getID 7
extern  int * getid_1();
extern  int * getid_1_svc();
extern int banco_1_freeresult ();
#endif /* K&R C */
#define CAIXA 2

#if defined(__STDC__) || defined(__cplusplus)
extern  int * deposita_2(dep *, CLIENT *);
extern  int * deposita_2_svc(dep *, struct svc_req *);
extern  int * retira_2(ret *, CLIENT *);
extern  int * retira_2_svc(ret *, struct svc_req *);
extern  float * consulta_2(int *, CLIENT *);
extern  float * consulta_2_svc(int *, struct svc_req *);
extern  int * getid_2(void *, CLIENT *);
extern  int * getid_2_svc(void *, struct svc_req *);
extern int banco_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
extern  int * deposita_2();
extern  int * deposita_2_svc();
extern  int * retira_2();
extern  int * retira_2_svc();
extern  float * consulta_2();
extern  float * consulta_2_svc();
extern  int * getid_2();
extern  int * getid_2_svc();
extern int banco_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_abre (XDR *, abre*);
extern  bool_t xdr_info (XDR *, info*);
extern  bool_t xdr_dep (XDR *, dep*);
extern  bool_t xdr_ret (XDR *, ret*);

#else /* K&R C */
extern bool_t xdr_abre ();
extern bool_t xdr_info ();
extern bool_t xdr_dep ();
extern bool_t xdr_ret ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BANCOV2_H_RPCGEN */
