/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bancoV2.h"


/*void
banco_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	abre  abreconta_1_arg;
	int  *result_2;
	int  fechaconta_1_arg;
	int  *result_3;
	info  autentica_1_arg;
	int  *result_4;
	dep  deposita_1_arg;
	int  *result_5;
	ret  retira_1_arg;
	float  *result_6;
	int  consulta_1_arg;
	int  *result_7;
	char *getid_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, BANCO, AGENCIA, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif

	result_1 = abreconta_1(&abreconta_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = fechaconta_1(&fechaconta_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = autentica_1(&autentica_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = deposita_1(&deposita_1_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = retira_1(&retira_1_arg, clnt);
	if (result_5 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = consulta_1(&consulta_1_arg, clnt);
	if (result_6 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = getid_1((void*)&getid_1_arg, clnt);
	if (result_7 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif
}


void
banco_2(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	dep  deposita_2_arg;
	int  *result_2;
	ret  retira_2_arg;
	float  *result_3;
	int  consulta_2_arg;
	int  *result_4;
	char *getid_2_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, BANCO, CAIXA, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif

	result_1 = deposita_2(&deposita_2_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = retira_2(&retira_2_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = consulta_2(&consulta_2_arg, clnt);
	if (result_3 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = getid_2((void*)&getid_2_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif
}*/

void abreC(long cpf, CLIENT * sv);
void fecha(long cpf, CLIENT * sv);
void aut(long cpf, CLIENT * sv);
void depos(long cpf, CLIENT * sv);
void retir(long cpf, CLIENT * sv);
void cons(long cpf, CLIENT * sv);


int
main (int argc, char *argv[])
{
	CLIENT *sv;
	int t;

	if (argc != 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}


	printf("\n1 - Agencia\n2 - Caixa\n");
	scanf("%d",&t);

	if(t == 1)
	{
		sv = clnt_create (argv[1], BANCO, AGENCIA, "udp");
	}
	else
	{
		sv = clnt_create (argv[1], BANCO, CAIXA, "udp");
	}	

	if (sv == NULL) {
		clnt_pcreateerror (argv[1]);
		exit (1);
	}

	while(1)
	{
		printf("\n");

		long cpf;
		int op;
		
		if(t == 1)
		{

			printf("digite o CPF do cliente\n");
			scanf("%ld",&cpf);

			printf("\n1 - Abertura de Conta\n2 - Fechamento de Conta\n");
			printf("3 - Deposito\n");
			printf("4 - Saque\n5 - Consulta de Saldo\n");
			scanf("%d",&op);
			printf("\n");

			switch(op)
			{
				case 1:
					abreC(cpf, sv);
					break;
				case 2:
					fecha(cpf, sv);
					break;
				case 3:
					depos(cpf, sv);
					break;
				case 4:
					retir(cpf, sv);
					break;
				case 5:
					cons(cpf, sv);
					break;
			}
		}
		else if(t == 2)
		{
			printf("Digite seu CPF\n");
			scanf("%ld",&cpf);

			printf("1 - Deposito\n");
			printf("2 - Saque\n3 - Consulta de Saldo\n");
			scanf("%d",&op);
			printf("\n");

			switch(op)
			{
				case 1:
					depos(cpf, sv);
					break;
				case 2:
					retir(cpf, sv);
					break;
				case 3:
					cons(cpf, sv);
					break;
			}
		}

	}

	exit (0);
}

void abreC(long cpf, CLIENT * sv)
{
	int senha;
	abre params;
	int * result;
	int * id;

	printf("Digite a senha para sua conta (4 digitos)\n");
	scanf("%d",&senha);

	params.cpf = cpf;
	params.senha = senha;

	do{
		id = getid_1(NULL, sv);
	}while(id == (int *) NULL);

	params.id = *id;

	printf("Teste : cpf %ld : senha %d : id %d\n",params.cpf,params.senha,params.id);

	do{
		result = abreconta_1(&params, sv);
	}while(result == (int *) NULL);

	printf("Conta aberta com sucesso!\n");
}

void fecha(long cpf, CLIENT * sv)
{
	int senha;
	info params;
	int * result;
	int * id;
	int numConta;

	printf("Digite a senha da sua conta (4 digitos)\n");
	scanf("%d",&senha);

	params.cpf = cpf;
	params.senha = senha;

	do{
		numConta = autentica_1(params, sv);
	}while(id == (int *) NULL);

	do{
		id = getid_1(NULL, sv);
	}while(id == (int *) NULL);

	do{
		result = fechaconta_1(&params, sv);
	}while(result == (int *) NULL);

	printf("Conta aberta com sucesso!\n");
}

void aut(long cpf, CLIENT * sv)
{
}

void depos(long cpf, CLIENT * sv)
{
}

void retir(long cpf, CLIENT * sv)
{

}

void cons(long cpf, CLIENT * sv)
{

}