/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "test.h"


/*void
prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	param  add_1_arg;
	int  *result_2;
	param  sub_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PROG, VERSAO, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif

	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = sub_1(&sub_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG
}
*/

int add(CLIENT * sv, int x, int y)
{
	param params;
	int * result;

	printf("Requisição add!\n");

	params.x = x; params.y = y;

	result = add_1(&params, sv);

	if(result == NULL)
	{
		printf("Problema na chamada RPC\n");
		exit(0);
	}

	return *result;
}

int sub(CLIENT * sv, int x, int y)
{
	param params;
	int * result;

	printf("Requisição sub!\n");

	params.x = x; params.y = y;

	result = sub_1(&params, sv);

	if(result == NULL)
	{
		printf("Problema na chamada RPC\n");
	}

	return *result;
}

int main (int argc, char *argv[])
{
	CLIENT *sv;
	int x,y;

	if (argc != 4) {
		printf ("usage: %s server_host num1 num2\n", argv[0]);
		return 1;
	}

	sv = clnt_create (argv[1], PROG, VERSAO, "udp");

	if (sv == NULL) {
		clnt_pcreateerror (argv[1]);
		return 1;
	}

	x = atoi(argv[2]); y = atoi(argv[3]);

	printf("%d + %d = %d\n", x, y, add(sv,x,y));
	printf("%d - %d = %d\n", x, y, sub(sv,x,y));

	return 0;
}
